version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # RADAR: Doing it the other way around because https://stackoverflow.com/a/70221693, but it might cause issues
    # network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: service:app
    environment:
      POSTGRES_USER: rubytoolbox
      POSTGRES_DB: rubytoolbox_development
      POSTGRES_PASSWORD: rubytoolbox

  redis:
    # We don't set up persistence here, so please be aware that your redis data will go away
    # on container restarts!
    image: redis:7.0
    restart: unless-stopped
    network_mode: service:app

volumes:
  postgres-data:
