local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage", Rails.env) %>

s3:
  service: S3
  endpoint: <%= ENV.fetch("S3_ENDPOINT_URL", nil) %>
  bucket: <%= ENV.fetch("S3_BUCKET", nil) %>
  region: <%= ENV.fetch("S3_REGION", "auto") %>
  access_key_id: <%= ENV.fetch("S3_ACCESS_KEY_ID", nil) %>
  secret_access_key: <%= ENV.fetch("S3_SECRET_ACCESS_KEY", nil) %>
