name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        # See https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
        bundler-cache: true
    - name: Run bundler-audit
      run: bundle exec bundler-audit --update

  brakeman:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run brakeman
      run: bundle exec brakeman

  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers#creating-service-containers
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: secret

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Install dependencies and run RSpec
      env:
        DATABASE_URL: "postgresql://postgres:secret@localhost/test"
        RAILS_ENV: test
        PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}
      run: |
        npm install
        bundle exec rake db:schema:load
        npm exec percy exec -- bundle exec rspec

    - uses: actions/upload-artifact@v4
      with:
        name: "Test Coverage"
        path: coverage/
